version: "3.8"  # docker engine version

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports: 
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # persist data even if container shuts down
      
volumes:
  database-data: # named volumes can be managed easier using docker-compose